export const createTypedControllerHelperContent = (appIdentifier: string) => `/*----------------------------------
- GENERATED FILE
----------------------------------*/

// This file is generated by Proteum from server/index.ts.
// Do not edit it manually.

import {
    defineAction as defineBaseAction,
    defineController,
    schema,
} from '@server/app/controller';
import type {
    TControllerActionContext,
    TControllerActionDefinition,
    TControllerActionInput,
    TControllerActionResult,
    TControllerDefinition,
    TValidationSchema,
    TValidationShape,
    z,
} from '@server/app/controller';

export { defineController, schema };
export type {
    TControllerActionDefinition,
    TControllerActionInput,
    TControllerActionResult,
    TControllerDefinition,
    TValidationSchema,
    TValidationShape,
    z,
};

export type TApplication = import('@/server/index').${appIdentifier};
export type TControllerRequestServices = import('@/server/index').TControllerRequestServices;
export type TTypedControllerActionContext<TInput = undefined> = TControllerActionContext<
    TInput,
    TApplication,
    TControllerRequestServices
>;

export function defineAction<TSchema extends TValidationSchema, TResult>(
    definition: {
        input: TSchema;
        handler: (context: TTypedControllerActionContext<z.output<TSchema>>) => TResult;
    },
): TControllerActionDefinition<z.output<TSchema>, TResult, TApplication, TControllerRequestServices>;
export function defineAction<TShape extends TValidationShape, TResult>(
    definition: {
        input: TShape;
        handler: (context: TTypedControllerActionContext<z.output<z.ZodObject<TShape>>>) => TResult;
    },
): TControllerActionDefinition<z.output<z.ZodObject<TShape>>, TResult, TApplication, TControllerRequestServices>;
export function defineAction<TResult>(
    definition: {
        handler: (context: TTypedControllerActionContext<undefined>) => TResult;
    },
): TControllerActionDefinition<undefined, TResult, TApplication, TControllerRequestServices>;
export function defineAction(definition: {
    input?: TValidationSchema | TValidationShape;
    handler: (context: TTypedControllerActionContext<any>) => unknown;
}) {
    return defineBaseAction(definition as any);
}
`;
