import path from 'path';

import app from '../../app';
import cli from '../..';
import { generateControllerClientTree, indexControllers, printControllerTree } from '../common/controllers';
import { TProteumManifestController } from '../common/proteumManifest';
import writeIfChanged from '../writeIfChanged';
import { normalizeAbsolutePath } from './shared';

const getManifestScopeFromImportPath = (importPath: string) =>
    importPath.startsWith('@server/controllers/') ? 'framework' : 'app';

export const generateControllerArtifacts = () => {
    const controllers = indexControllers([
        { importPrefix: '@server/controllers/', root: path.join(cli.paths.core.root, 'server', 'controllers') },
        { importPrefix: '@/server/controllers/', root: path.join(app.paths.root, 'server', 'controllers') },
    ]);
    const manifestControllers = controllers.flatMap<TProteumManifestController>((controller) =>
        controller.methods.map((method) => ({
            className: controller.className,
            importPath: controller.importPath,
            filepath: normalizeAbsolutePath(controller.filepath),
            sourceLocation: method.sourceLocation,
            routeBasePath: controller.routeBasePath,
            methodName: method.name,
            inputCallsCount: method.inputCallsCount,
            hasInput: method.inputCallsCount > 0,
            routePath: method.routePath,
            httpPath: '/api/' + method.routePath,
            clientAccessor: method.routePath.split('/').join('.'),
            scope: getManifestScopeFromImportPath(controller.importPath),
        })),
    );
    const clientTree = generateControllerClientTree(controllers);

    const getControllerLeafMeta = (leaf: string) => {
        const meta = JSON.parse(leaf) as {
            routePath: string;
            importPath: string;
            className: string;
            methodName: string;
            hasInput: boolean;
        };
        const controllerIndex = controllers.findIndex((controller) => controller.importPath === meta.importPath);

        if (controllerIndex === -1) {
            throw new Error(`Unable to find controller import ${meta.importPath} while generating controller types.`);
        }

        return { ...meta, controllerIndex };
    };

    const runtimeLeaf = (leaf: string) => {
        const meta = getControllerLeafMeta(leaf);
        const resultType = `TControllerResult<Controller${meta.controllerIndex}, ${JSON.stringify(meta.methodName)}>`;

        return meta.hasInput
            ? `(data) => api.createFetcher<${resultType}>('POST', ${JSON.stringify(meta.routePath)}, data)`
            : `() => api.createFetcher<${resultType}>('POST', ${JSON.stringify(meta.routePath)})`;
    };

    const typeImports = controllers
        .map((controller, index) => `import type Controller${index} from ${JSON.stringify(controller.importPath)};`)
        .join('\n');

    const typeLeaf = (leaf: string) => {
        const meta = getControllerLeafMeta(leaf);
        const fetcherType = `TControllerFetcher<Controller${meta.controllerIndex}, ${JSON.stringify(meta.methodName)}>`;

        return meta.hasInput ? `(data: any) => ${fetcherType}` : `() => ${fetcherType}`;
    };

    const createControllersContent = `/*----------------------------------
- GENERATED FILE
----------------------------------*/

// This file is generated by Proteum from server controller files.
// Do not edit it manually.

import type ApiClient from '@common/router/request/api';
import type { TFetcher } from '@common/router/request/api';
${typeImports ? '\n' + typeImports : ''}

type TControllerResult<TController, TMethod extends keyof TController> =
    TController[TMethod] extends (...args: any[]) => infer TResult ? Awaited<TResult> : never;

type TControllerFetcher<TController, TMethod extends keyof TController> = TFetcher<TControllerResult<TController, TMethod>>;

export type TControllers = ${printControllerTree(clientTree, typeLeaf)};

export const createControllers = (
    api: Pick<ApiClient, 'createFetcher'>
): TControllers => (
${printControllerTree(clientTree, runtimeLeaf)}
);

export default createControllers;
`;

    writeIfChanged(path.join(app.paths.common.generated, 'controllers.ts'), createControllersContent);

    writeIfChanged(
        path.join(app.paths.client.generated, 'controllers.ts'),
        `export { createControllers, default } from '@generated/common/controllers';
export type { TControllers } from '@generated/common/controllers';
`,
    );

    const controllerImports = controllers
        .map((controller, index) => `import Controller${index} from ${JSON.stringify(controller.importPath)};`)
        .join('\n');

    const controllerEntries = controllers.flatMap((controller, controllerIndex) =>
        controller.methods.map(
            (method) => `    {
        path: ${JSON.stringify('/api/' + method.routePath)},
        filepath: ${JSON.stringify(normalizeAbsolutePath(controller.filepath))},
        sourceLocation: { line: ${method.sourceLocation.line}, column: ${method.sourceLocation.column} },
        Controller: Controller${controllerIndex},
        method: ${JSON.stringify(method.name)},
    },`,
        ),
    );

    writeIfChanged(
        path.join(app.paths.server.generated, 'controllers.ts'),
        `/*----------------------------------
- GENERATED FILE
----------------------------------*/

// This file is generated by Proteum from server controller files.
// Do not edit it manually.

import type Controller from '@server/app/controller';
${controllerImports ? '\n' + controllerImports : ''}

export type TGeneratedControllerDefinition = {
    path: string,
    filepath: string,
    sourceLocation: { line: number, column: number },
    Controller: new (request: any) => Controller,
    method: string,
}

const controllers: TGeneratedControllerDefinition[] = [
${controllerEntries.join('\n')}
];

export default controllers;
`,
    );

    return manifestControllers;
};
